services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: bankingpw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  banking-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5224"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5224
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=banking;Username=banking;Password=bankingpw
    depends_on:
      - db

volumes:
  pgdata:
